# Generated by Django 5.1.5 on 2025-06-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expensesplitbetween_owe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplitbetween',
            name='amount_owed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
