# Generated by Django 5.1.5 on 2025-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_settlement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='expense',
        ),
    ]
