# Generated by Django 5.1.5 on 2025-06-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.group'),
        ),
    ]
